version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '%(asctime)s | %(levelname)s | %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

loggers:
  app_logger:
    level: INFO
    handlers: [console]
    propagate: no
